### ISSUE TITLE
RoomEditor texture preview

### ISSUE THREAD

**Issue by cyberjunk** [Meridian59/Meridian59#219] opened 2013-07-27 16:14 UTC
The texture preview in the RoomEditor fails until you put an absolute path to the BGF files in windeu.ini (instead of the relative one).

Yes - it initializes them correctly with the relative one, but the preview fails.

**Comment by jrotunda** [comment] 2022-09-30 22:43
@davidklaw I think this is what caused the problems with the initial Kocatan room kod

**Comment by davidklaw** [comment] 2023-03-18 22:10
I personally haven't had any trouble previewing textures, assuming we're talking about this preview you see when double-clicking texture names in the LineDef edit window:

![image](https://user-images.githubusercontent.com/467443/226142883-fbf826c0-4b39-441e-8569-8ca2ba7661d7.png)

**Comment by davidklaw** [comment] 2023-04-08 21:35
@Meridian59 I'm unable to reproduce this issue nowadays, going back to my previous comment at least. My BGF resources path is relative in `windeu.ini` and my texture previews render just fine. I'm thinking we can close it.

**Closed** 2023-04-11 20:25 UTC
