### ISSUE TITLE
Art: Room: The Granary in East Jasper (jas-east.roo) is missing textures on the roof.

### ISSUE THREAD

**Issue by jrotunda** [Meridian59/Meridian59#715] opened 2024-05-11 10:09 UTC
In East Jasper, one of the buildings (the Granary) has missing textures for a large chunk of the roof. 

The building is in plain view of the player and the missing roof can be seen from in front of the building and the street.

A small portion of the roof (with texture) is visible on the section to the side of the silo, but there's nothing for the front and back slopes, allowing the player to see through to the wall/sky behind it.

- The textures should match the other parts of the roof (the cobblestone), unless the designer working on this .roo in the room editor can come up with something they think looks more visually interesting.

Attached:

Photo 1 - Above View (not accessible by player)
Photo 2 and 3 - Player View
Photo 4 - Map view of the building, not marked on the East Jasper Map. Yes, the room is that large.

![East Jasper - Granary - Map View](https://github.com/Meridian59/Meridian59/assets/2608213/66b4f2fc-a10c-4f09-9959-7d344a1a5200)
![East Jasper - Granary - Missing Roof 2 - Street View](https://github.com/Meridian59/Meridian59/assets/2608213/fece6ec7-d3f0-4117-8edf-4aadfbcc9b06)
![East Jasper - Granary - Missing Roof 3 - Front Right](https://github.com/Meridian59/Meridian59/assets/2608213/ec3b99ca-1aa1-4227-8fba-04f083962b83)
![East Jasper - Granary - Missing Roof 1](https://github.com/Meridian59/Meridian59/assets/2608213/50690f28-17a5-4d8d-b1ac-1ac8113eb303)

**Comment by Gar103** [comment] 2024-05-15 04:12
Funnily enough, I kinda think this should be preserved, just made more cohesive. I always assumed the granary barn roof had collapsed.

**Comment by davidklaw** [comment] 2024-08-15 11:20
> Funnily enough, I kinda think this should be preserved, just made more cohesive. I always assumed the granary barn roof had collapsed.

That's a neat idea I unfortunately didn't catch before I corrected this in #856. From what I saw doing that, it appeared to be unintentional and caused by intersecting lines. I think this can be closed for now.

**Comment by davidklaw** [comment] 2024-08-21 11:26
@Meridian59 This one is fixed now.

**Closed** 2024-08-21 12:18 UTC
