### ISSUE TITLE
Delete is Not Called Before Objects are Freed

### ISSUE THREAD

**Issue by ememisya** [Meridian59/Meridian59#386] opened 2022-03-27 21:43 UTC
Might I suggest something like

```
   if (IsInterpreting())
      SendBlakodMessage(object_id,DELETE_MSG,0,NULL);
   else
      SendTopLevelBlakodMessage(object_id,DELETE_MSG,0,NULL);

   /* now remove object */
```

Prepended to

https://github.com/Meridian59/Meridian59/blob/6a57ad3cd2a156d81c4cd93697a13d71621fb971/blakserv/object.c#L349

?

**Comment by akirmse** [comment] 2022-03-28 02:47
I'm pretty sure the current behavior is correct.  Delete() is not meant to be called anytime an object is garbage collected; it's not like a finalizer in Java.  It's an explicit function that's called directly from Blakod.

**Comment by ememisya** [comment] 2022-03-28 03:29
The issue I believe with NecromancerAmulet 
 was that Delete is never called if a garbage collection occurs and an amulet was left alone in a room somewhere https://github.com/Meridian59/Meridian59/blob/409c0af357c668f476fc2fc24a5e6826fd242d4b/kod/object/item/actitem/necroam.kod which is crucial in maintaining the necromancer balance since the item count in Object 1 depends on that function to be called.  I thought https://www.youtube.com/watch?v=9gtsw3-8lBs would demonstrate this a little better.

**Comment by Meridian59** [comment] 2022-03-28 15:49
I'm not too familiar with the Necro scenario, but it does sound like it's
implemented incorrectly.  Can you propose a Blakod-only fix?  I don't think
we want to start calling Blakod during garbage collection.

I wonder if this might be related to a similar problem with some NPCs like
Maleval who sometimes wind up with multiple copies.

**Comment by davidklaw** [comment] 2022-07-31 13:06
I'm still scratching my head a bit on this one, but in confirming this is still the case I can see that this affects the count of generated hunter's swords as well.

As @ememisya mentioned, the constructor is incrementing and Delete() would decrement, but isn't called during garbage collection:

```
Constructor()
   {
      pbCounted = TRUE;
      send(send(SYS,@GetNecromancerBalance),@IncrementAmuletCount);   <-----
      propagate;
   }

Delete()
   {
      debug("Delete() is being called in necroam.kod");

      if pbCounted
      {
         pbCounted = FALSE;
         send(send(SYS,@GetNecromancerBalance),@DecrementAmuletCount);   <-----
      }
      if ptHungerTimer <> $ {
         deleteTimer(ptHungerTimer);
         ptHungerTimer = $;
      }
      if ptHoldingDamage <> $ {
         deleteTimer(ptHoldingDamage);
         ptHoldingDamage = $;
      }
      %have to post this so that in case the item gets deleted out of the blue while in use, it still has the stat mod data when delete() propagates down to unusing the item.
      post(self,@postDelete);
      propagate;
   }
```

**Comment by davidklaw** [comment] 2022-07-31 15:05
I wonder, is it appropriate to tap into `TriggerAmuletGeneration()` or `GenerateAmulet()` in the [NecromancerBalance class](https://github.com/Meridian59/Meridian59/blob/master/kod/util/necbal.kod) (`necbal.kod`) and update the generated count before using it to determine if more should be generated?

**Comment by ememisya** [comment] 2022-07-31 22:39
> I'm still scratching my head on this one, but in confirming this is still the case I can see that this affects the count of generated hunter's swords as well.
> 
> As discussed, the constructor is incrementing and Delete() would decrement, but isn't called during garbage collection:
> 
> ```
> Constructor()
>    {
>       pbCounted = TRUE;
>       send(send(SYS,@GetNecromancerBalance),@IncrementAmuletCount);   <-----
>       propagate;
>    }
> 
> Delete()
>    {
>       if pbCounted
>       {
>          pbCounted = FALSE;
>          send(send(SYS,@GetNecromancerBalance),@DecrementAmuletCount);   <-----
>       }
>       if ptHungerTimer <> $ {
>          deleteTimer(ptHungerTimer);
>          ptHungerTimer = $;
>       }
>       if ptHoldingDamage <> $ {
>          deleteTimer(ptHoldingDamage);
>          ptHoldingDamage = $;
>       }
>       %have to post this so that in case the item gets deleted out of the blue while in use, it still has the stat mod data when delete() propagates down to unusing the item.
>       post(self,@postDelete);
>       propagate;
>    }
> ```

A similar question was posed in the Java world.  The finalize method stuck around until JDK9 at which point it was replaced by Cleaners.  From the docs on the reason for the deprecation:

> The finalization mechanism is inherently problematic. Finalization can lead to performance issues, deadlocks, and hangs. Errors in finalizers can lead to resource leaks; there is no way to cancel finalization if it is no longer necessary; and no ordering is specified among calls to finalize methods of different objects. Furthermore, there are no guarantees regarding the timing of finalization. The finalize method might be called on a finalizable object only after an indefinite delay, if at all. Classes whose instances hold non-heap resources should provide a method to enable explicit release of those resources, and they should also implement AutoCloseable if appropriate. The Cleaner and PhantomReference provide more flexible and efficient ways to release resources when an object becomes unreachable.

The interesting part is Delete is called exclusively for almost every interaction in the codebase, except for the Necromancer balance.  However it's not necessarily incorrectly implemented should @Delete behave like a finalizer.  The object it is referencing can be traced from System as it is "static", so I compared it to its time (preserving the spirit) and thought that must be what they meant to do when they coded it and offered my suggestion.

One of the authors of the language stated the following:

> I'm pretty sure the current behavior is correct. Delete() is not meant to be called anytime an object is garbage collected; it's not like a finalizer in Java. It's an explicit function that's called directly from Blakod.

Given Mr. Kirmse is one of the original authors it is clear to me now that the intention was never to go the finalizer route Java took at the time.

**Comment by jrotunda** [comment] 2022-09-30 22:01
DELETE itself is working as intended...when used by USERS - but it definitely can cause game breaking issues in $ if any steps are skipped.

Fattymoo (NDS era admin, see design doc "Mike's Changes") was afraid to delete an item once and said I had to do it because he didn't want to mess with it. I know understand why the NDS admin was nervous. 

As mentioned by Andrew, this may be related to how if you create an object of a specific class it won't be deleted unless the server is reset. 

I think I figured out what objects this occurs for and why.

This is definitely one of those items that needs its in game methods of removal obeyed or else it has lingering side effects. The side effect could simply be an added and unneeded resource - or it could be game breaking and very embarrassing. 

** Bug: if you use the delete command on anything that had a separate, specific MSG assigned to its class to call for a delete - and needs to be deleted by those methods such as actions in game or inactions like allowing timers to expire - it doesn't work right anymore, only exists visually, but not functional and the object stays stuck in the servers resources and the class listing. Sending it to inventories or rooms will send a "phantom duplicate" of the same object.

I know there are exceptions to this - you eat a meat pie, it deletes it, but it also deletes fine when send that command - likely because eating it doesn't just call for the delete, it calls for messages too.

Blakod is good at deleting  - but doesn't like it when you ask it to delete something without following assigned deletion protocols. It doesn't like it if you create or activate things that have another command that calls for that either. 


Ex: NPC dupes. Regular NPCs can't be deleted. Bugs in the past were caused when NPCs - which have the DELETE MSG alone - couldn't be removed.

If you put a room inside a room - the room that is on the inside gets deleted. You can still go it and it's a visual nightmare but it has to be remade. Don't ask why I know this.

If you put a USER inside an object that they can't be in - like a table - the user gets deleted. They can be pulled out of the table but their character is dead and they can't commit suicide to clear their character slot.

I'm having a problem right now with a rentable room key copy - the key was deleted in $, but won't clear from the active objects of that class. The proper way to delete a key is handing to the innkeeper, which calls for a delete to the item.

I also saw this in testing: a faction Shield on a user will never be deleted and will stay as an object in the Class if the shield isn't lost by a normal method. 

Or even on a user! _users can type "suicide" which calls for that Users Object to be deleted. But if you delete a user it makes it so that the object can not interact with the world in a functional way, only exist in it.

It doesn't exist but can still be summoned to inventory of any object and handed to an innkeeper - but it's never deleted by the innkeeper. They take it and it goes into the void and can be found again after a garbage collection and save. 


This affects every NPC, it doesn't affect Roq, who isn't a real NPC (he is a shell for the assassin game kod itself and you can make multiple Assassin objects and delete them with bow issue on a live server)


I'm able to add \ remove  Hunter Sword and Necro Objects in $admin for creating objects - however using the Messages for the Class to call the function doesn't behave the same, and doing the above would have the same result.

Note:

The Necromancer scenario was ripped out and only fragments remain - any remaining bits of this scenario aren't expected to be working correctly if tinkered with, but there may be something else with the $admin variants of delete that is causing this problem.

**Closed** 2023-03-31 01:43 UTC
