### ISSUE TITLE
Xeo attacks are overly aggressive

### ISSUE THREAD

**Issue by Meridian59** [Meridian59/Meridian59#27] opened 2013-01-21 05:09 UTC
When there > 100 players online (or whatever the threshold is set to be), Xeo attacks seem to spawn continually, instead of being periodic.

**Comment by qorkod** [comment] 2021-12-16 08:16
The frequency of attacks can be changed in the settings (Object 55 usually), however there does seem to be some built up timer factoring in beyond that, where all attackable nodes get hit over and over no matter what it’s set to. This can continues for up to 6 nodes. 

The admin has to reset the timer or turn the min users on back up. It may have something to do with adjusting the frequency setting instead of users online.

Its suggested that the node attack timer not exist at all  in nodeatk.kod as there is already a frequency setting doing the work here. 

Warning: to send the node to users without them binding with it through gameplay can cause an issue as well where the players can get the node twice.

**Comment by davidklaw** [comment] 2022-07-31 18:37
It looks to like there's initially a 2-day waiting period before nodes can come under attack. After that node attack ends, the waiting period becomes 36 days. Wait times like this are stored in an array for the nodes (ex. `[36, 36, 36, 36, 36, 36, 36]`). Without having tested it yet, the code seems to suggest that all of these decrement at the same rate. Because of this, once one node attack occurs, it won't be long before the next one days because the other wait times will be similarly low (but chosen at random). With enough players on, I think you could potentially see a wave of node attacks followed by a long period of no attacks. Does that sound like it describes the problem y'all see?

**Comment by davidklaw** [comment] 2022-08-08 02:37
I discussed this with @jrotunda and after watching these play out on 101 today and going up and down the code, I'm unable to find the issue or an issue does not exist. I thought it might have something to do with timers, but here's my thinking:

> A new day begins in Meridian.
> Checks to see if wait between attacks is 0 (and a node isn't already under attack) and if so, a timer is started with a wait time between 1 minute and 4 hours. When this timer completes, it will attempt to trigger a node attack, and if it fails, it will try again 1-2 hours later. At this same time, the timing of the next node attack is set to 36 days later.
> At this point, `ptAttack` is this this attack timer (line 229)
> When the criteria for a node attack is met, a node attack begins. `ptAttack` is nullified and eventually for a new timer (line 367).
> The node attack continues for 60 minutes. After 60 minutes or if all Xeos are killed, the node attack is ended. Any existing `ptAttack` timer is deleted.
> If a new day rolled over while a node was being attacked, nothing would happen.
> If a new day rolls over after a node attack has ended, the wait time will decrement and should do so for another 30+ Meridian days before the next node attack occurs.

@skittles1 added [this commit ](https://github.com/OpenMeridian/Meridian59/commit/3b1958bdc96c65809af4bc7b43ed944e1aaf5a7c#) to OpenMeridian, but I haven't been able to confirm whether or not it was to address or attempt to address this issue.

I'm going to give up on this one and hope that if it is still an issue, someone benefits from my notes.

**Comment by jrotunda** [comment] 2022-08-08 03:31
Based on observation after running the node attacks normally with some tweaks to the "attack intensity" (keep this low; scale up based on player base, amount, skill and aggression levels) "attack time" (which controls how long players have, helps to give them time if not aggressive player base), "loss duration" and "severed chance" (which control gameplay negative affect if populace fails, also low so attacks aren't too annoying) the node attacks aren't doing anything that they shouldn't do when running normally, using the settings in the node attack object to manage them based on a servers activity level. 

The issues observed in the past seem to likely be due to misunderstanding of the live code and messages associated with Node Attack that allow them to be handled manually. Further testing will be done of these messages to see what, if any bugs are being caused by them when a Normal Node attack is in progress. 

For now the node attacks will be left active and enabled on 101 to both collect further data if there is any issue with them and allow players to enjoy the various endgame content** having them on also unlocks. 

Suggest this issue can be closed, and more detailed and specific issue-fixes if any can be made after further observation.



** Heartstones, dropped by dead Xeo, are used as regents for several powerful "endgame" spells like BOND, which is costly and one of the bigger targets to reach as a mage or to have on your items. 

They're also needed for the rentable rooms to create storage boxes and other objects - which are impermanent objects, "recycled", good from a storage/memory and gameplay standpoint.

**Comment by akirmse** [comment] 2022-08-08 04:23
Closing.  Someone reported this a long time ago if I remember right.

**Closed by akirmse** 2022-08-08 04:23 UTC
Labels: Zaphod's requests
