### ISSUE TITLE
Death link is not working

### ISSUE THREAD

**Issue by The-Rippa** [Meridian59/Meridian59#357] opened 2018-09-29 20:33 UTC
Tried all kinds of things.  Currently death link uses a lot of expensive regs and does nothing.  It would be nice if it actually worked.

**Comment by akirmse** [comment] 2018-09-29 22:48
What do you see when you try it?

**Comment by The-Rippa** [comment] 2018-09-30 01:27
it casts and the icon comes up on screen that it is active,  but it does nothing.  no matter how many mobs die on screen, it doesnt do anything.

**Comment by qorkod** [comment] 2021-12-14 05:06
Can confirm that Death Link currently has no effect.

The spell is an area effect for the room and will use mana, vigor and reagents when cast. 

It’s expected that when a monster is killed while this area effect spell is up, players with negative karma receive a small amount of vigor.

**Comment by jrotunda** [comment] 2022-07-07 04:22
I tested Death Link again and the spell functions as designed. I suggest this issue be closed as it does work.

The caster will gain a small amount of mana and vigor from every kill in a given area while this area enchantment is in effect on a room.

It’s not very noticeable because the gain isn’t that high, but this can be addressed separately in the spell kod in a PR.

**Comment by davidklaw** [comment] 2022-07-31 16:10
According to the description of Death Link and the following method in the kod file, DL will deal out a small amount of health and mana to the caster. For each, DL will roll a random value from 1 and 5 and then multiply it by 4, so the caster will see a 4-20 point increase in health and a 4-20 point increase in mana.

Notes:
* The spellpower only dictates duration, not the health/mana boost
* There doesn't appear to be a karma requirement for receiving the health/mana boost, only casting
* The karmic value of the monster killed doesn't appear to affect whether or not the boost is given

My own tests also confirm that Death Link is technically working. @Meridian59 I think this can be closed. @The-Rippa if you truly find that it's not working, please provide more details to help reproduce the issue. If you simply feel it's underpowered that's valid feedback, too. Share any thoughts you might have about improving it.

**Closed** 2022-07-31 22:15 UTC
